### ISSUE TITLE
missing BlynkSimpleSimpleNB.h

### ISSUE THREAD

**Issue by Thomas-GeDaD** [techstudio-design/SimpleNB#1]
Hi,
thanks for the nice work.
The Sim7080 modem works fine with your library.
Want to use the Blynk example. Where can i finde the BlynkSimpleSimpleNB.h ?
https://github.com/techstudio-design/SimpleNB/blob/29121af2ed273f7d2d8033d09ce86ffb7c890678/examples/BlynkClient/BlynkClient.ino#L42

**Comment by techstudio-design** [comment]
My apology. I was supposed to remove this example as I don't use Blynk and never test it.

The include is supposed to be `#include <BlynkSimpleTinyGSM.h>` which is part of [BlynkLibrary](https://github.com/techstudio-design/SimpleNB/issues/1).

The example uses the API for establishing a GSM/GPRS type of connection, so I'm not sure that it will works with SimpleNB as it solely focus on 4G/NB-IoT, you could give it a try. If it not working, you will have to change the `Blynk.begin()` parameters or switch to uses the `TinyGSM` library.

**Comment by Thomas-GeDaD** [comment]
Hi,
thanks for the information. 
So we will further use the https connection. This works fine for us. 
In tinygsm there are several issues with the sim7080g, because of this we use your library.
Thanks for this.. ;-)
