### ISSUE TITLE
Quectel BG95 support

### ISSUE THREAD

**Issue by A-n-d-y-K** [techstudio-design/SimpleNB#4]
[x] I have read the Troubleshooting section of the ReadMe

## What type of issues is this?

[x] Request to support a new module
    
[ ] Bug or problem compiling the library
[ ] Bug or issue with library functionality (ie, sending data over TCP/IP)
[ ] Question or request for help

### What are you working with?

Modem: Quectel BG95
Main processor board: N/A 
SimpleNB version: latest master 
Code: N/A

### Scenario, steps to reproduce

N/A

### Request
As per [Supported Features](https://github.com/techstudio-design/SimpleNB#supported-features) Quectel BG96 is supported by SimpleNB. 
Does SimpleNB also support [Quectel BG95](https://www.quectel.com/product/lpwa-bg95-cat-m1-cat-nb2-egprs-series)?

- If yes, cool, great :-)
- If no, what needs to be done to support BG95

Info [BG95&BG96 Series Difference Introduction](https://www.quectel.com/wp-content/uploads/2021/07/Quectel_BG95BG96_Series_Difference_Introduction_V1.0.pdf)

Thanks much for your support

### Actual result

N/A

### Debug and AT command log

N/A

**Comment by techstudio-design** [comment]
No, BG95 is currently not supported. Even though it looks similar to BG96, we currently don't have any BG95 with us for testing and adding the support for BG95.  More importantly, there is no commercial cases/requests for us to spend time on it now. 

For BG96, we did add SSL support as it was not working or doesn't supported by TinyGSM.

Quectel modules in general are quite similar to SimCom modules (the founder of Quectel (and many engineers) are ex-SimCom), they changes many of the commands (for example, AT+CENG, AT+CSQ to AT+QENG, AT+QSQ, which is quite silly and unnecessary), but there are some timing issue and internal state management that could caused some behaviour and timing differences, and therefore need to run tests before we say it is supported.

**Comment by A-n-d-y-K** [comment]
Dear @techstudio-design ,
thanks for your your answer and the nice insights abour Quectel history. I´ll close this issue.
